### ISSUE TITLE
routes.routes is an empty array if the handler is defined in config object

### ISSUE THREAD

**Issue by pdehaan** [brianoneil/require-hapiroutes#1]
If you define your `handler` function in the `config` object, then it doesn't seem to get added to the `routes.routes` array:

For example:

``` js
// routes/foo.js
module.exports = {
  method: 'GET',
  path: '/foo',
  config: {
    handler: function (request, reply) {
      reply('/foo');
    }
  }
};
```

``` js
// routes/bar.js
module.exports = {
  method: 'GET',
  path: '/bar',
  config: {
    handler: function (request, reply) {
      reply('/bar');
    }
  }
};
```

``` js
// routes/index.js
var requireHapiRoutes = require('require-hapiroutes');
module.exports = requireHapiRoutes(module);

console.log(module.exports);
```

The `module.exports` object is:

``` js
{ bar: { method: 'GET', path: '/bar', config: { handler: [Function] } },
  foo: { method: 'GET', path: '/foo', config: { handler: [Function] } },
  routes: [] }
```

Note that it still seems to detect the routes `foo`, and `bar`, but the `routes` array doesn't get populated, meaning that in my index.js file you cant use:

``` js
var routes = require('./routes');
server.route(routes.routes);
```

Instead, you have to manually define your routes using:

``` js
var routes = require('./routes');
server.route([
  routes.foo,
  routes.bar
]);
```

For more Hapi information, see:
- http://hapijs.com/api#route-configuration
- http://hapijs.com/api#route-options -- which says that the `config` object can contain:
  
  > `handler` - an alternative location for the route `handler` option.

**Comment by brianoneil** [comment]
Okay, I will take a look at that.  I have not included it there before.  Should be an easy fix.  I will try to get it in tonight.

**Comment by pdehaan** [comment]
Looking through the source code, it looks like I can do an `exports.routes = [{...}];` as a workaround since it doesn't seem like those are validated:

``` js
exports.routes = [
  {
    method: 'GET',
    path: '/foo',
    config: {
      handler: function (request, reply) {
        reply('/foo');
      }
    }
  }
];
```

Which generates this:

``` js
{ bar: { routes: [ [Object] ] },
  foo: { routes: [ [Object] ] },
  routes:
   [ { method: 'GET', path: '/bar', config: [Object] },
     { method: 'GET', path: '/foo', config: [Object] } ] }
```

**Comment by brianoneil** [comment]
I already pushed a fix to github. I just need to publish on npm.

**Comment by pdehaan** [comment]
I think that may work. I'd be mildly concerned about this use case:

```
    if(Array.isArray(routeModule) && routeModule.length > 0 && routeModule[0].hasOwnProperty('handler') && routeModule[0].hasOwnProperty('path')) {
      debug('this looks like an array for some reason')
      Array.prototype.push.apply(routes, routeModule);
    }
```

So if I'm reading that correctly, if I have this, it potentially wouldn't match since in this path you're checking for a top level `handler` and `path` (instead of a potential nested `config.handler`):

``` js
module.exports = [
  {
    path: '/',
    config: {
      handler: function (request, reply) {
        reply('ok');
      }
   }
 }
];
```

**Comment by pdehaan** [comment]
OK, here's my quick and hacky 2 minute solution for this:

``` js
function isRoute(route) {
  var hasHandler = route.handler || (route.config && route.config.handler);
  var hasPath = route.path;
  return hasHandler && hasPath;
}
```

Instead of using `routeModule.hasOwnProperty('...')` I just test the module and let it return a truthy value or not (you could also cast it out to a Boolean if you prefer using `!!`). So that let me simplify the code somewhat to a central validator function above and then this code:

``` js
    if(Array.isArray(routeModule) && routeModule.length > 0 && isRoute(routeModule[0])) {
      debug('this looks like an array for some reason');
      Array.prototype.push.apply(routes, routeModule);
    }

    else if(isRoute(routeModule)){
      debug('loading module as a route file: %s', keys[i]);
      routes.push(routeModule);
    }
```

Seems to work for my 4 test cases, but I didn't try git cloning and running your unit tests.

**Comment by brianoneil** [comment]
yes, I updated that...  as you said, that is where it didn't find it.  I
add "or" cases to allow it to load with it in either place.

**Comment by pdehaan** [comment]
Yeah, but I think your commit only added the OR clauses to the `else if (...) {}` and not to the `if (Array.isArray(...)) {}` path.

**Comment by brianoneil** [comment]
Ah, good call.  I like the isRoute function anyway, it is cleaner.  I just integrated this and I am pushing an update now.  I will go ahead and publish on npm as well.  Thanks for the feedback on this!

**Comment by pdehaan** [comment]
Thanks for the great module!
